// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Chat     string
	Contact  string
	Message  string
	User     string
	UserChat string
}{
	Chat:     "chat",
	Contact:  "contact",
	Message:  "message",
	User:     "user",
	UserChat: "user_chat",
}
