services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ../volumes/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    platform: linux/amd64
    restart: always

  db_migrator:
    image: golang:1.17-alpine3.14
    volumes:
      - ../..:/go/src/github.com/halfdb/herro-world
    working_dir: /go/src/github.com/halfdb/herro-world
    environment:
      DB_STRING: root:$MYSQL_ROOT_PASSWORD@tcp(db:3306)/$MYSQL_DATABASE?parseTime=true
    command: sh -c "apk add build-base && go install github.com/pressly/goose/v3/cmd/goose@v3.3.1 && ./scripts/wait-for.sh db:3306 -t 300 && make db-up && nc -lk -p 4242 -e cat"
    ports:
      - 4242:4242

  herro_server:
    image: golang:1.17-alpine3.14
    volumes:
      - ../..:/go/src/github.com/halfdb/herro-world
    working_dir: /go/src/github.com/halfdb/herro-world
    environment:
      JWT_SECRET: $JWT_SECRET
      PORT: $PORT
      DB_STRING: root:$MYSQL_ROOT_PASSWORD@tcp(db:3306)/$MYSQL_DATABASE?parseTime=true
    ports:
      - $PORT:$PORT
    command: sh -c "go install github.com/halfdb/herro-world/cmd/server && ./scripts/wait-for.sh db_migrator:4242 -t 3000 -- server"
